from openpyxl import load_workbook

def send_light(ui, path):
    wb = load_workbook(path, read_only=True, data_only=True)
    ws = wb['Hoja1']

    ui.LookAheadDistMin.setText   (str(ws.cell(5,6).value))
    ui.LookAheadDistMax.setText   (str(ws.cell(6,6).value))
    ui.LookBackDistMin.setText    (str(ws.cell(8,6).value))
    ui.LookBackDistMax.setText    (str(ws.cell(9,6).value))
    ui.W74ax.setText              (str(ws.cell(12,6).value))
    ui.W74bxAdd.setText           (str(ws.cell(13,6).value))
    ui.W74bxMult.setText          (str(ws.cell(14,6).value))
    ui.MaxDecelOwn.setText        (str(ws.cell(17,6).value))
    ui.MaxDecelTrail.setText      (str(ws.cell(18,6).value))
    ui.DecelRedDistOwn.setText    (str(ws.cell(19,6).value))
    ui.DecelRedDistTrail.setText  (str(ws.cell(20,6).value))
    ui.AccDecelOwn.setText        (str(ws.cell(21,6).value))
    ui.AccDecelTrail.setText      (str(ws.cell(22,6).value))
    ui.DiffusTm.setText           (str(ws.cell(23,6).value))
    ui.SafDistFactLnChg.setText   (str(ws.cell(25,6).value))
    ui.CoopDecel.setText          (str(ws.cell(26,6).value))
    ui.MinCollTmGain.setText      (str(ws.cell(35,6).value))
    ui.MinSpeedForLat.setText     (str(ws.cell(36,6).value))
    ui.LatDistStandDef.setText    (str(ws.cell(38,7).value))
    ui.LatDistDrivDef.setText     (str(ws.cell(39,7).value))
    wb.close()

def send_minors(ui, path):
    wb = load_workbook(path, read_only=True, data_only=True)
    ws = wb['Hoja1']

    ui.LookAheadDistMin.setText   (str(ws.cell(5,8).value))
    ui.LookAheadDistMax.setText   (str(ws.cell(6,8).value))
    ui.LookBackDistMin.setText    (str(ws.cell(8,8).value))
    ui.LookBackDistMax.setText    (str(ws.cell(9,8).value))
    ui.W74ax.setText              (str(ws.cell(12,8).value))
    ui.W74bxAdd.setText           (str(ws.cell(13,8).value))
    ui.W74bxMult.setText          (str(ws.cell(14,8).value))
    ui.MaxDecelOwn.setText        (str(ws.cell(17,8).value))
    ui.MaxDecelTrail.setText      (str(ws.cell(18,8).value))
    ui.DecelRedDistOwn.setText    (str(ws.cell(19,8).value))
    ui.DecelRedDistTrail.setText  (str(ws.cell(20,8).value))
    ui.AccDecelOwn.setText        (str(ws.cell(21,8).value))
    ui.AccDecelTrail.setText      (str(ws.cell(22,8).value))
    ui.DiffusTm.setText           (str(ws.cell(23,8).value))
    ui.SafDistFactLnChg.setText   (str(ws.cell(25,8).value))
    ui.CoopDecel.setText          (str(ws.cell(26,8).value))
    ui.MinCollTmGain.setText      (str(ws.cell(35,8).value))
    ui.MinSpeedForLat.setText     (str(ws.cell(36,8).value))
    ui.LatDistStandDef.setText    (str(ws.cell(38,9).value))
    ui.LatDistDrivDef.setText     (str(ws.cell(39,9).value))
    wb.close()

def send_public(ui, path):
    wb = load_workbook(path, read_only=True, data_only=True)
    ws = wb['Hoja1']

    ui.LookAheadDistMin.setText   (str(ws.cell(5,10).value))
    ui.LookAheadDistMax.setText   (str(ws.cell(6,10).value))
    ui.LookBackDistMin.setText    (str(ws.cell(8,10).value))
    ui.LookBackDistMax.setText    (str(ws.cell(9,10).value))
    ui.W74ax.setText              (str(ws.cell(12,10).value))
    ui.W74bxAdd.setText           (str(ws.cell(13,10).value))
    ui.W74bxMult.setText          (str(ws.cell(14,10).value))
    ui.MaxDecelOwn.setText        (str(ws.cell(17,10).value))
    ui.MaxDecelTrail.setText      (str(ws.cell(18,10).value))
    ui.DecelRedDistOwn.setText    (str(ws.cell(19,10).value))
    ui.DecelRedDistTrail.setText  (str(ws.cell(20,10).value))
    ui.AccDecelOwn.setText        (str(ws.cell(21,10).value))
    ui.AccDecelTrail.setText      (str(ws.cell(22,10).value))
    ui.DiffusTm.setText           (str(ws.cell(23,10).value))
    ui.SafDistFactLnChg.setText   (str(ws.cell(25,10).value))
    ui.CoopDecel.setText          (str(ws.cell(26,10).value))
    ui.MinCollTmGain.setText      (str(ws.cell(35,10).value))
    ui.MinSpeedForLat.setText     (str(ws.cell(36,10).value))
    ui.LatDistStandDef.setText    (str(ws.cell(38,11).value))
    ui.LatDistDrivDef.setText     (str(ws.cell(39,11).value))
    wb.close()

def send_hgv(ui, path):
    wb = load_workbook(path, read_only=True, data_only=True)
    ws = wb['Hoja1']

    ui.LookAheadDistMin.setText   (str(ws.cell(5,12).value))
    ui.LookAheadDistMax.setText   (str(ws.cell(6,12).value))
    ui.LookBackDistMin.setText    (str(ws.cell(8,12).value))
    ui.LookBackDistMax.setText    (str(ws.cell(9,12).value))
    ui.W74ax.setText              (str(ws.cell(12,12).value))
    ui.W74bxAdd.setText           (str(ws.cell(13,12).value))
    ui.W74bxMult.setText          (str(ws.cell(14,12).value))
    ui.MaxDecelOwn.setText        (str(ws.cell(17,12).value))
    ui.MaxDecelTrail.setText      (str(ws.cell(18,12).value))
    ui.DecelRedDistOwn.setText    (str(ws.cell(19,12).value))
    ui.DecelRedDistTrail.setText  (str(ws.cell(20,12).value))
    ui.AccDecelOwn.setText        (str(ws.cell(21,12).value))
    ui.AccDecelTrail.setText      (str(ws.cell(22,12).value))
    ui.DiffusTm.setText           (str(ws.cell(23,12).value))
    ui.SafDistFactLnChg.setText   (str(ws.cell(25,12).value))
    ui.CoopDecel.setText          (str(ws.cell(26,12).value))
    ui.MinCollTmGain.setText      (str(ws.cell(35,12).value))
    ui.MinSpeedForLat.setText     (str(ws.cell(36,12).value))
    ui.LatDistStandDef.setText    (str(ws.cell(38,13).value))
    ui.LatDistDrivDef.setText     (str(ws.cell(39,13).value))
    wb.close()